rails/activerecord-session_store

- lib/action_dispatch/session/active_record_store.rb
- test/action_controller_test.rb
`ActiveRecord::Base.logger.quietly` will be deprecated in future release of Rails, and it is not thread safe, so this method is removed on this occasion.
Also one more deprecated syntax is fixed.
> Remove and fix methods for deprecation warning in rails 4 2

- lib/active_record/session_store/session.rb
- test/session_test.rb
Fixes rails/activerecord-session_store#6
> Preserve Session construction compatibility without attr_accessible

- lib/active_record/session_store/session.rb
I'm running into an error where I'm unable to call `create!` on a `Session` when including the Protected Attributes gem (latest 1.1.3). The Protected Attributes gem adds an options hash as the second argument to `Session.new`, but the initialize method for `Session` only accepts a single argument.  
```
Failure/Error: session_to_delete = ActiveRecord::SessionStore::Session.create!(:session_id => "abc7f90d0c2190a161d46af004c6c78c", :data => "")
ArgumentError:
wrong number of arguments calling `initialize` (2 for 1)
```
Since the `Session` object extends `ActiveRecord::Base` which has an initialize method with a signature like `def initialize(attributes = nil, options = {})` ([reference](https://github.com/rails/rails/blob/4-0-stable/activerecord/lib/active_record/core.rb#L170)), and the …
> Fix initialize signature to match ActiveRecord::Base

- README.md
We may as well use the generic path to set configuration in the README as per the Rails core documentation.
It provides one less change the user has to make and also allows the renaming of applications down the road very slightly easier (no need to change "MyApp" to the new name).
I've tested this in a live app and it's functioning correctly. Let me know what you think.
Thanks. :)
> Use generic namespace rather than App-specific

- lib/active_record/session_store/extension/logger_silencer.rb
Send logs further if logdev not defined.
> Fix Syslog::Logger logs

- lib/tasks/database.rake
- test/tasks/database_rake_test.rb
Hello,
This PR adds a rake task to delete old sessions from the table, without clearing the entire table.
Many thanks,
Oli
> Rake task to trim old sessions

- lib/active_record/session_store/session.rb
The current implementation lead to `DEPRECATION WARNING`s under Rails 5 and ultimately prevented records from being saved. If I interpret the code right, the `return false` statements are not meant for halting the whole saving chain but just mean to exit the method. I've replaced them with a simple `return` and everything appears to work.
Thanks a bunch for considering this.
> Do not use 'return false' in AR callbacks for compatibility with Rails 5

- lib/tasks/database.rake
Truncate table is more efficient when deleting all table data
> Use Truncate instead of delete while clearing sessions

- README.md
- lib/active_record/session_store.rb
I've been using this in my application using Postgres' [JSONB data type](https://www.postgresql.org/docs/current/static/datatype-json.html) for the data column and it is working well for my needs. For example I can use something like the code below to get a list of sessions so the user can select one to log out:
``` ruby
Session.where(%(data @> '{"user_id": ?}'), current_user.id)
```
I'm unsure what the best way is to go about adding tests for this - do we need to add PostgreSQL/MySQL to the test suite?
> Add NullSerializer for JSON database columns

- activerecord-session_store.gemspec
I don't think much is gained by having an upper-limit dependency on AP/AR/Railties. It just forces you guys to make a release for every minor version of this gem. Im not sure if that actually helps us in any way.
> No upper-bound dependency for AR/AP/Railties

- test/action_controller_test.rb
- test/destroy_session_test.rb
- test/helper.rb
After #120 I noticed there were some deprecation warnings for Rails 6:
1. `DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0`
2. `DEPRECATED: Use assert_nil if expecting nil`
> [CHORE] Fix Rails 6 deprecations

- lib/active_record/session_store.rb
Use lazy-load hook:
- When requiring `active_record/session_store/session`, it will load the `ActiveRecord::Base` [class](https://github.com/rails/activerecord-session_store/blob/a170dd4016208b9ce45cb77f2d946d2d7ef8064e/lib/active_record/session_store/session.rb#L7) which triggers all lazy load hooks at the wrong time
> Use lazy-load hook:

- lib/action_dispatch/session/active_record_store.rb
As stated in #130 this improves the performance of `delete_session` in case there is no existing session.
The `delete_session` method uses the [`get_session_model` method](https://github.com/rails/activerecord-session_store/blob/3e0147c74f862dc9a3600a8b11c980d9d43897a1/lib/action_dispatch/session/active_record_store.rb#L101) which creates a [new instance if no existing is found](https://github.com/rails/activerecord-session_store/blob/3e0147c74f862dc9a3600a8b11c980d9d43897a1/lib/action_dispatch/session/active_record_store.rb#L125-L134) only to [destroy it afterwards](https://github.com/rails/activerecord-session_store/blob/3e0147c74f862dc9a3600a8b11c980d9d43897a1/lib/action_dispatch/session/active_record_store.rb#L101-L107). Using `@@session_class.find_by_session_id(id)` instead (which is …
> Improved performance of delete_session in case there is none

- lib/tasks/database.rake
Remove the `supports_migrations?` check:
- This method is deprecated as of Rails 5.1. All tested databases seems to supports migrations since at least rails/rails@a4fc93c
- Ref rails/rails#28172
> Remove the `supports_migrations?` check:

- lib/action_dispatch/session/active_record_store.rb
- lib/active_record/session_store.rb
Hi there,
I stumbled across an issue when using `activerecord-session_store` via bundlers inline functionality:
```
/path/to/gems/ruby-2.4.2/gems/activerecord-session_store-1.1.0/lib/action_dispatch/session/active_record_store.rb:151:in `<top (required)>': uninitialized constant ActiveRecord::VERSION (NameError)
from /path/to/gems/ruby-2.4.2/gems/activerecord-session_store-1.1.0/lib/active_record/session_store.rb:2:in `require'
from /path/to/gems/ruby-2.4.2/gems/activerecord-session_store-1.1.0/lib/active_record/session_store.rb:2:in `<top (required)>'
from /path/to/gems/ruby-2.4.2/gems/activerecord-session_store-1.1.0/lib/activerecord/session_store.rb:1:in `require'
from /path/to/gems/ruby-2.4.2/gems/activerecord-session_store-1.1.0/lib/activerecord/session_store.rb:1:in `<top …
```
> Fixed: uninitialized constant ActiveRecord::VERSION (NameError).

- .travis.yml
- activerecord-session_store.gemspec
- gemfiles/rails_4.0.gemfile
- gemfiles/rails_4.1.gemfile
- gemfiles/rails_4.2.gemfile
- gemfiles/rails_5.0.gemfile
- gemfiles/rails_5.1.gemfile
This should fix the build failures on `master`, getting the branch ready for release of next version.
This PR includes:
* Lock sqlite3 to ~> 1.3.6 on Rails <= 2.5.2, as those version has `gem "sqlite3", "~> 1.3.6"` in them.
* Remove appraisal from development dependency.
* Add Ruby 2.6.1 to the build matrix.
* Remove Ruby 2.4 from edge Rails since edge Rails now require Ruby 2.5+.
> Lock sqlite3 to ~> 1.3.6 on Rails <= 2.5.2, and update Travis build matrix

- lib/active_record/session_store.rb
- lib/active_record/session_store/session.rb
- Fixes #142
-  The goal of #126 was to lazily require the 'session.rb' file as
otherwise, we'd load `Active::Record` base too prematurely during
the boot process.
This change had the negative effect of breakin apps that were
setting configuration on the `Session` **before** the hook was
getting triggered, thus ending up with a "uninitialized constant"
error.
This patches move the `session_class` assignment when loading then
`session.rb` file as well as autoloading the
`AR::SessionStore::Session` constant so that application referencing
it too early will still work.
> Fix backward compatibility issue introduced by #126

- README.md
CVE-2015-9284 is an old CSRF Bug in Omniauth, has nothing to do with
CVE-2019-25025 which is a timing attack against session ids.
> Fix CVE in README

- activerecord-session_store.gemspec
- gemfiles/rails_edge.gemfile
- test/action_controller_test.rb
This updates some version requirements and adopts to the api of rack-test 2.
This includes the changes from https://github.com/rails/activerecord-session_store/pull/194
> Fix main branch build

- lib/action_dispatch/session/active_record_store.rb
With the current implementation it is not possible for different subclasses to use different session models since it uses a class variable to access it which is shared amongst inherited classes.
This changes uses the accessor method instead which can be overridden by the subclass(es).
This includes the changes from #194 to make the pipeline work again
> Allow subclasses of session store to override session_class

- .github/workflows/ci.yml
- gemfiles/rails_7.2.gemfile
- gemfiles/rails_8.0.gemfile
- test/helper.rb
- test/logger_silencer_test.rb
Fix: https://github.com/rails/activerecord-session_store/pull/219
Starting from https://github.com/rails/rails/pull/49819 most of the test suite is broken.
I'm trying to figure out how to fix it, but I'm really struggling to make sense of it.
@gmcgibbon would you have a bit of time to look at this? I think I managed to fix the `build_app` and `with_routing` things, but now it seems like cookies aren't set.
FYI: @stevenharman
> Fix test suite with Rails 7.2+

- .github/workflows/ci.yml
- CHANGELOG.md
- activerecord-session_store.gemspec
- gemfiles/rails_6.1.gemfile
- gemfiles/rails_7.0.gemfile
- test/action_controller_test.rb
- test/helper.rb
- test/with_integration_routing_patch.rb
I took another look at the changes we had to make in #220 and compared that to how things work in `actiondispatch`'s Cookie Store tests and realized we were close, but missing how we were setting the options for our store. So I've revamped the setup to be in line with what's in Rails' own tests. This should make it easier to keep things in line and working, going forward.
See the following two files for how Cookie Store tests (and their base `ActionDispatch::IntegrationTest`) work today (as of Rails 8.0):
* https://github.com/rails/rails/blob/8-0-stable/actionpack/test/dispatch/session/cookie_store_test.rb
* https://github.com/rails/rails/blob/8-0-stable/actionpack/test/abstract_unit.rb
The big downside to this is… it depends on some changes to how `#with_routing`, provided by Rails, …
> Use a test setup similar to `actiondispatch`'s Cookie Store tests

- README.md
- lib/action_dispatch/session/active_record_store.rb
- test/action_controller_test.rb
- test/helper.rb
- test/with_integration_routing_patch.rb
This change allows the disabling of fallback used to access old, insecure sessions, and rewrite them as secure sessions. The fallback was originally added as part of the mitigation of [CVE-2019-25025](https://github.com/advisories/GHSA-cvw2-xj8r-mjf7) several years back.
This fallback mechanism was [added 4 years ago](https://github.com/rails/activerecord-session_store/pull/151). In many cases, or at least in our case, the expiry on old, insecure, sessions has long since passed. We'd like the ability to disable the fallback entirely as it will never be a valid path for us.
> Allow use of secure session only
